<?php

namespace Devlabs\SportifyBundle\Entity;

/**
 * PredictionChampionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredictionChampionRepository extends \Doctrine\ORM\EntityRepository
{
}
