<?php

namespace Devlabs\SportifyBundle\Entity;

/**
 * PredictionWinnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredictionWinnerRepository extends \Doctrine\ORM\EntityRepository
{
}
