<?php

namespace Devlabs\SportifyBundle\Entity;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the first team for a tournament from the DB
     *
     * @param Tournament $tournament
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getFirstByTournament(Tournament $tournament)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('tm')
            ->from('DevlabsSportifyBundle:Team', 'tm')
            ->join('tm.tournaments', 'tr')
            ->where('tr.id = :tournament_id')
            ->setParameters(array(
                'tournament_id' => $tournament->getId()
            ))
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * Get all teams for given tournament
     *
     * @param Tournament $tournament
     * @return array
     */
    public function getAllByTournament(Tournament $tournament)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('tm')
            ->from('DevlabsSportifyBundle:Team', 'tm')
            ->join('tm.tournaments', 'tr')
            ->where('tr.id = :tournament_id')
            ->setParameters(array(
                'tournament_id' => $tournament->getId()
            ))
            ->getQuery()
            ->getResult();
    }
}
